# Generated by Django 6.0.1 on 2026-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Укажите заголовок", max_length=100, verbose_name="Заголовок")),
                (
                    "body",
                    models.TextField(blank=True, help_text="Введите содржимое", null=True, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Превью поста",
                        null=True,
                        upload_to="feedback/images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, help_text="дата создания поста", null=True, verbose_name="дата создания"
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите кол-во просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Записи",
                "ordering": ["title", "body", "created_at", "view_counter"],
            },
        ),
    ]
