# Generated by Django 6.0.1 on 2026-01-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Категория с продуктами", max_length=100, verbose_name="Категория"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Описание категории с продуктами", null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Наименование Продукта", max_length=100, verbose_name="Продукт")),
                (
                    "description",
                    models.CharField(blank=True, help_text="Описание Продукта", null=True, verbose_name="Описание"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение продукта",
                        null=True,
                        upload_to="products/images",
                        verbose_name="Изображение",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "created_at",
                    models.DateField(
                        blank=True, help_text="дата создания продукта", null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="дата последнего изменения продукта",
                        null=True,
                        verbose_name="дата изменения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Категория продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "created_at", "updated_at", "value"],
            },
        ),
    ]
